project:
  type: website

website:
  title: "Predicting Gallstone"
  navbar:
    left:
      - href: subgroups.qmd
        text: Subgroups
      - href: exploration.qmd
        text: Exploration
      - href: replication.qmd
        text: Replication
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



